sonar.python.version=3.10,3.11,3.12,3.13,3.14
sonar.tests=paramiko_cloud/aws/test_keys.py,paramiko_cloud/azure/test_keys.py,paramiko_cloud/dummy/test_keys.py,paramiko_cloud/gcp/test_keys.py,paramiko_cloud/test_grpc_server.py,paramiko_cloud/test_helpers.py,paramiko_cloud/test_pki.py
